# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: app
    build: .
    command: gunicorn -b 0.0.0.0:5000 app.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=${MYSQL_DATABASE_URI}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./app:/code/app
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: app
    command: "celery worker -A app.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
networks:
    default:
        external:
            name: ${EXT_NETWORK_NAME}
